#!/usr/bin/env python3
"""Connection-emission parity check for a Maestro Case solution.

A Maestro Case that calls an Integration Service connector must declare that
connector as a *solution* resource. That declaration is derived, not authored:
`caseplan.json` `bindings[]` -> `bindings_v2.json` `resources[]` -> emitted
`resources/<folder>/connection/<connectorKey>/<name>.json`. Every step is a
projection of the previous one, and each is regenerated by a separate command.

When any link is skipped, the case still packs and publishes — with zero
connector declarations in the package. Nothing in the toolchain reports it:
`uip solution resources refresh` returns `Result: Success` with
`Warnings: []` and `Synced 0 resources` when the sidecar is empty (there is
nothing to resolve, so nothing to warn about), `uip maestro case validate`
returns `Valid`, and `pack` / `publish` both succeed. The failure surfaces only
to whoever opens or runs the case, as `<connectorKey> is not found`.

This check compares the three declaration sites plus what the caseplan actually
calls, and fails when they disagree.

    A = distinct connectionIds in caseplan.json bindings[] (resource=Connection)
    B = Connection entries in bindings_v2.json resources[]
    C = emitted resources/*/connection/*/*.json files
    D = distinct connectorKeys the caseplan references

    require A == B == C, and every key in D to have an emitted resource

`D` is not redundant with the count parity: when `A` and `B` are both empty the
comparison passes trivially at 0 while the case still calls a connector.

Read-only, stdlib only. Exit 0 = parity holds, 1 = do not pack or publish.

Usage:
    check_connection_parity.py <solutionDir> [--quiet]
"""

import json
import pathlib
import re
import sys

PLACEHOLDER_KEY = "placeholder"

# caseplan stores a connector key two ways: as a plain field, and as an entry in
# a task's `context` array. Both occur in real builds; miss the second and a
# fully-broken caseplan reports zero connector references.
_KEY_PLAIN = re.compile(r'"connectorKey\\?"\s*:\s*\\?"([a-z0-9\-]+)')
_KEY_CONTEXT = re.compile(
    r'"name\\?"\s*:\s*\\?"connectorKey\\?".{0,80}?"value\\?"\s*:\s*\\?"([a-z0-9\-]+)',
    re.S,
)


def _caseplan_connections(plan):
    """Distinct connection ids declared in caseplan bindings[].

    Read the way the consumer reads it. `case-bindings-service.ts` writes the
    sidecar's ConnectionId as `attributeDefault(group, "ConnectionId") ?? key`,
    so a ConnectionId binding with no `default` falls back to its own
    `resourceKey` — which for a connection IS the connection id, and the
    sidecar comes out correct. Requiring `default` here counted a working
    binding as zero and reported a parity break that did not exist.

    Not checked here: a folder-key binding with no `default` has no such
    fallback and silently drops the folder key. That is a real defect, and
    `uip maestro case validate --strict` reports it as
    STRICT_CONNECTION_FOLDER_KEY_NO_DEFAULT — this script does not duplicate it.
    """
    return {
        b.get("default") or b.get("resourceKey")
        for b in plan.get("bindings", []) or []
        if b.get("resource") == "Connection"
        and str(b.get("propertyAttribute", "")).lower() == "connectionid"
        and (b.get("default") or b.get("resourceKey"))
    }


def _sidecar_connections(project_dir):
    sidecar = project_dir / "bindings_v2.json"
    if not sidecar.exists():
        return set(), False
    try:
        resources = json.loads(sidecar.read_text()).get("resources", []) or []
    except json.JSONDecodeError as exc:
        sys.exit(f"FAIL: {sidecar} is not valid JSON: {exc}")
    return {r.get("key") for r in resources if r.get("resource") == "Connection"}, True


def check(solution_dir, quiet=False):
    solution_dir = pathlib.Path(solution_dir)
    caseplans = sorted(solution_dir.glob("*/caseplan.json"))
    if not caseplans:
        if not quiet:
            print(f"SKIP: no */caseplan.json under {solution_dir} — not a case solution")
        return 0

    failures = []
    for caseplan in caseplans:
        project = caseplan.parent
        raw = caseplan.read_text()
        try:
            plan = json.loads(raw)
        except json.JSONDecodeError as exc:
            sys.exit(f"FAIL: {caseplan} is not valid JSON: {exc}")

        a_ids = _caseplan_connections(plan)
        b_ids, sidecar_exists = _sidecar_connections(project)
        emitted = sorted(solution_dir.glob("resources/*/connection/*/*.json"))
        emitted_keys = {p.parent.name for p in emitted}
        called_keys = set(_KEY_PLAIN.findall(raw)) | set(_KEY_CONTEXT.findall(raw))
        # An unresolved connector rule carries the literal `connectorKey: "placeholder"`
        # by contract (connector-trigger-impl.md § stub). That is a declared-unresolved
        # marker, not a connector the case can call, so it needs no emitted resource —
        # counting it would fail a correctly-placeholdered build.
        called_keys.discard(PLACEHOLDER_KEY)
        missing_keys = called_keys - emitted_keys

        if not quiet:
            print(f"  {project.name}:")
            print(f"    caseplan connections   A = {len(a_ids)}")
            print(f"    bindings_v2 entries    B = {len(b_ids)}"
                  f"{'' if sidecar_exists else '  (bindings_v2.json absent)'}")
            print(f"    emitted resources      C = {len(emitted)}  {sorted(emitted_keys)}")
            print(f"    connectorKeys called   D = {len(called_keys)}  {sorted(called_keys)}")

        if len(a_ids) != len(b_ids):
            failures.append(
                f"{project.name}: caseplan declares {len(a_ids)} connection(s) but "
                f"bindings_v2.json has {len(b_ids)} — the sidecar was not regenerated "
                f"after the caseplan was written"
            )
        if len(b_ids) != len(emitted):
            failures.append(
                f"{project.name}: bindings_v2.json has {len(b_ids)} Connection entry(ies) "
                f"but {len(emitted)} resource file(s) on disk — run "
                f"`uip solution resources refresh` before packing"
            )
        for key in sorted(missing_keys):
            failures.append(
                f"{project.name}: caseplan calls connector '{key}' with no emitted "
                f"resource under resources/*/connection/{key}/"
            )

    if failures:
        print("BLOCKED: connector(s) referenced by the case are not declared as solution "
              "resources. Do not pack or publish.")
        for f in failures:
            print(f"  - {f}")
        return 1

    if not quiet:
        print("OK: every connector the case calls is declared as a solution resource")
    return 0


def main(argv):
    args = [a for a in argv[1:] if not a.startswith("-")]
    if len(args) != 1:
        print(__doc__.strip().splitlines()[-1].strip(), file=sys.stderr)
        return 2
    return check(args[0], quiet="--quiet" in argv[1:])


if __name__ == "__main__":
    sys.exit(main(sys.argv))
