#!/usr/bin/env python3
"""Assert the artifact left behind by the Coded Function redirect.

The uipath-agents skill must recognise deterministic logic as a Coded Function
and hand off to uipath-functions (SKILL.md Critical Rule 1). The redirect is
graded on which skill engaged and which CLI lifecycle ran; this script grades
what the handoff produced, so a redirect that names the right skill but emits
an agent scaffold still fails:

  1. `uipath.json` carries a non-empty `functions` entrypoint map — the
     defining marker Critical Rule 1 keys on.
  2. No `<framework>.json` is present — a langgraph.json / llama_index.json /
     openai_agents.json alongside a functions map means a framework agent was
     scaffolded and the map hand-added after the fact.
  3. `entry-points.json` (generated by `uip function init`) agrees with the
     functions map — this is what proves `init` ran against the real code.
  4. `@traced()` decorates the entry function, satisfying the prompt's
     Orchestrator trace-visibility requirement.
"""

from __future__ import annotations

import ast
import json
import os
import re
import sys
from pathlib import Path

_shared_root = (
    os.path.join(os.environ["SKILLS_REPO_PATH"], "tests", "tasks", "uipath-agents")
    if os.environ.get("SKILLS_REPO_PATH")
    else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
sys.path.insert(0, _shared_root)

from _shared.project_root import find_project_root  # noqa: E402

ROOT = find_project_root("calc-agent")
FRAMEWORK_CONFIGS = ("langgraph.json", "llama_index.json", "openai_agents.json")
ENTRYPOINT_RE = re.compile(r"^\.?/?(?P<module>[\w/\-]+)\.py:(?P<func>\w+)$")


def fail(msg: str) -> None:
    sys.exit(f"FAIL: {msg}")


def load_json(path: Path) -> object:
    if not path.is_file():
        fail(f"Missing {path.relative_to(ROOT) if path.is_relative_to(ROOT) else path}")
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        fail(f"{path.name} is not valid JSON: {exc}")


def check_functions_map() -> tuple[Path, str, str]:
    """uipath.json declares exactly one `<file>.py:<func>` entrypoint."""
    doc = load_json(ROOT / "uipath.json")
    if not isinstance(doc, dict):
        fail("uipath.json is not a JSON object")

    functions = doc.get("functions")
    if functions is None:
        fail(
            "uipath.json has no `functions` key — this is the defining marker of a "
            "Coded Function project (setup.md § Coded Function Agents)"
        )
    if not isinstance(functions, dict) or not functions:
        fail(
            f"uipath.json `functions` must be a non-empty object mapping an entrypoint "
            f"name to `<file>.py:<function>`, got {functions!r}"
        )
    if len(functions) != 1:
        fail(f"Expected exactly one entrypoint in `functions`, got {sorted(functions)}")

    name, target = next(iter(functions.items()))
    if not isinstance(target, str):
        fail(f"`functions.{name}` must be a string, got {target!r}")

    match = ENTRYPOINT_RE.match(target)
    if not match:
        fail(f"`functions.{name}` = {target!r} does not match the `<file>.py:<function>` form")

    module_path = ROOT / f"{match.group('module')}.py"
    if not module_path.is_file():
        fail(f"`functions.{name}` points at {target!r} but {module_path.name} does not exist")

    return module_path, match.group("func"), name


def check_no_framework_config() -> None:
    present = [name for name in FRAMEWORK_CONFIGS if (ROOT / name).is_file()]
    if present:
        fail(
            f"Found framework config {present} alongside a `functions` map — this is a "
            f"framework agent, not a Coded Function. The scaffold is chosen by which "
            f"package is installed (build.md § Framework Reference)."
        )


def check_entry_points(entry_name: str) -> None:
    """`uip function init` must have recorded the same entrypoint.

    Match on the functions-map KEY, not the Python function name: `filePath`
    echoes the key (`{"main": "main.py:calculate"}` → `filePath: "main"`), so
    matching the function name only passes when the entry function happens to
    be called `main`.
    """
    doc = load_json(ROOT / "entry-points.json")
    if not isinstance(doc, dict):
        fail("entry-points.json is not a JSON object")

    entries = doc.get("entryPoints")
    if not isinstance(entries, list) or not entries:
        fail(f"entry-points.json has no `entryPoints` array — did `uip function init` run? Got: {doc!r}")

    names = [e.get("filePath") or e.get("uniqueId") or e.get("name") for e in entries if isinstance(e, dict)]
    if entry_name not in [str(n) for n in names if n]:
        fail(
            f"entry-points.json does not reference the `{entry_name}` entrypoint declared in "
            f"uipath.json (found: {names!r}) — schemas are out of sync with the code"
        )


def check_traced(module_path: Path, entry_func: str) -> None:
    """@traced() on the entry function, imported from uipath.tracing."""
    source = module_path.read_text()
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        fail(f"{module_path.name} does not parse: {exc}")

    imported = any(
        isinstance(node, ast.ImportFrom)
        and node.module == "uipath.tracing"
        and any(alias.name == "traced" for alias in node.names)
        for node in ast.walk(tree)
    )
    if not imported:
        fail(
            f"{module_path.name} does not import `traced` from `uipath.tracing` "
            f"(capabilities/tracing.md)"
        )

    def decorator_names(node: ast.AST) -> list[str]:
        names = []
        for dec in getattr(node, "decorator_list", []):
            target = dec.func if isinstance(dec, ast.Call) else dec
            if isinstance(target, ast.Name):
                names.append(target.id)
            elif isinstance(target, ast.Attribute):
                names.append(target.attr)
        return names

    functions = [
        node
        for node in ast.walk(tree)
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
    ]

    entry = next((fn for fn in functions if fn.name == entry_func), None)
    if entry is None:
        fail(f"{module_path.name} defines no function named `{entry_func}`")

    if "traced" not in decorator_names(entry):
        fail(
            f"`{entry_func}` is not decorated with @traced() — build.md requires it on simple "
            f"function agents for Orchestrator visibility (LangGraph gets tracing automatically)"
        )


def main() -> None:
    if not ROOT.is_dir():
        fail(f"Project directory {ROOT} does not exist")

    module_path, entry_func, entry_name = check_functions_map()
    check_no_framework_config()
    check_entry_points(entry_name)
    check_traced(module_path, entry_func)

    print(f"PASS: Coded Function shape verified ({module_path.name}:{entry_func}, @traced, no framework config)")


if __name__ == "__main__":
    main()
