#!/usr/bin/env python3
"""Critical Rule LC7 — the derived files carry no hand-authored drift.

`entry-points.json` and `bindings_v2.json` are generated by `uip agent
refresh`, never hand-written. Grading that by pattern-matching Write/Edit/shell
redirection is both leaky (every new spelling needs a new matcher) and too
strict (an edit the agent then supersedes with a real refresh is harmless).

Grade the invariant instead: **refresh is a fixed point.** Snapshot the derived
files, re-run `uip agent refresh`, and require the regenerated files to be
identical. That holds if and only if the agent ran refresh after its last edit —
which is what Critical Rule 2 asks for — and it holds regardless of how the
agent got there. A hand-edit that drifts from what `agent.json` generates fails;
a hand-edit the agent then overwrote with a genuine refresh passes, because the
on-disk state is the generated state.

The refresh is a probe, not a fix: the pre-refresh bytes are restored before
exit, so this check leaves the sandbox exactly as the agent left it and cannot
repair state that other criteria grade (`check_edit_roundtrip.py` asserts the
same files' contents, and criterion order must not matter).

Exits 0 on PASS, with a `FAIL: ...` message on drift.
"""

from __future__ import annotations

import os
import difflib
import json
import subprocess
import sys
from pathlib import Path

_shared_root = (
    os.path.join(os.environ["SKILLS_REPO_PATH"], "tests", "tasks", "uipath-agents")
    if os.environ.get("SKILLS_REPO_PATH")
    else os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
)
sys.path.insert(0, _shared_root)
from _shared.project_files import find_project_dir  # noqa: E402

CWD = Path.cwd()
PROJECT = find_project_dir("GreetSol", "GreeterAgent")

# Regenerated by refresh — the files under assertion.
DERIVED = ("entry-points.json", "bindings_v2.json")
# refresh also writes a migrated `agent.json` (step 2 of the command). Snapshot
# it so the restore is complete even when a migration fires; it is not asserted
# here — its content is graded by check_edit_roundtrip.py.
RESTORED = DERIVED + ("agent.json",)

DIFF_LINES = 40


def fail(msg: str) -> None:
    sys.exit(f"FAIL: {msg}")


def snapshot(names: tuple[str, ...]) -> dict[str, bytes | None]:
    """Raw bytes per file, or None when the file does not exist."""
    snap: dict[str, bytes | None] = {}
    for name in names:
        path = PROJECT / name
        snap[name] = path.read_bytes() if path.is_file() else None
    return snap


def restore(snap: dict[str, bytes | None]) -> None:
    for name, before in snap.items():
        path = PROJECT / name
        if before is None:
            if path.is_file():
                path.unlink()
        else:
            path.write_bytes(before)


def run_refresh() -> None:
    """Regenerate the derived files, or exit with a diagnosis."""
    try:
        proc = subprocess.run(
            ["uip", "agent", "refresh", str(PROJECT), "--output", "json"],
            capture_output=True, text=True, timeout=180,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        # A missing or hung CLI is a harness condition, not an agent mistake.
        print(f"SKIP: could not run `uip agent refresh` ({exc}) — drift unverified")
        sys.exit(0)

    if proc.returncode != 0:
        tail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-800:]
        fail(
            "`uip agent refresh` failed against the state the agent left behind, "
            "so the derived files cannot be verified. refresh runs static "
            "validation before writing, so this is the project failing that "
            f"gate (exit {proc.returncode}):\n{tail}"
        )


def normalized(raw: bytes) -> str | None:
    """Canonical JSON text, or None when the bytes are not JSON."""
    try:
        return json.dumps(json.loads(raw.decode("utf-8")), indent=2, sort_keys=True)
    except (UnicodeDecodeError, json.JSONDecodeError):
        return None


def diff(name: str, before: bytes, after: bytes) -> str:
    """Unified diff of the two versions, semantic where both parse as JSON."""
    b, a = normalized(before), normalized(after)
    if b is None or a is None:
        b = before.decode("utf-8", "replace")
        a = after.decode("utf-8", "replace")
    lines = list(
        difflib.unified_diff(
            b.splitlines(), a.splitlines(),
            fromfile=f"{name} (on disk)", tofile=f"{name} (regenerated)",
            lineterm="", n=2,
        )
    )
    if len(lines) > DIFF_LINES:
        lines = lines[:DIFF_LINES] + [f"... ({len(lines) - DIFF_LINES} more diff lines)"]
    return "\n".join(lines)


def compare(before: dict[str, bytes | None], after: dict[str, bytes | None]) -> None:
    for name in DERIVED:
        was, now = before[name], after[name]

        if was is None and now is None:
            print(f"OK: {name} is absent both before and after refresh")
            continue

        if was is None:
            fail(
                f"{name} did not exist until refresh generated it — the agent "
                f"never ran `uip agent refresh` after its edits (Critical Rule 2)"
            )

        if now is None:
            fail(
                f"refresh removed {name} — the on-disk copy was hand-authored and "
                f"nothing in agent.json generates it (Critical Rule LC7)"
            )

        nb, na = normalized(was), normalized(now)
        if nb is not None and na is not None and nb == na:
            print(f"OK: {name} is byte-for-byte what refresh regenerates")
            continue
        if nb is None and na is None and was == now:
            print(f"OK: {name} is unchanged by refresh")
            continue

        fail(
            f"{name} is not what `uip agent refresh` generates from agent.json — "
            f"it was hand-edited after the last refresh, which passes content "
            f"checks while breaking the regeneration contract (Critical Rule "
            f"LC7).\n{diff(name, was, now)}"
        )


def main() -> None:
    if not PROJECT.is_dir():
        fail(f"project directory {PROJECT} does not exist")
    if not (PROJECT / "agent.json").is_file():
        fail(f"Missing {(PROJECT / 'agent.json')} — nothing to regenerate from")

    before = snapshot(RESTORED)
    try:
        run_refresh()
        after = snapshot(RESTORED)
    finally:
        restore(before)

    compare(before, after)
    print("PASS: derived files match a fresh `uip agent refresh` — no manual drift")


if __name__ == "__main__":
    main()
